<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <title>PHP: Documentation Tools</title>

  <link media='all' rel='stylesheet' href='//shared.php.net/styles/defaults.css?filemtime=1421836947'/>
  <link media='all' rel='stylesheet' href='//shared.php.net/styles/doc.css?filemtime=1425812404'/>

  <link href="//fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,400italic,600italic|Source+Code+Pro&amp;subset=latin,latin-ext" rel="stylesheet">
  <link rel="shortcut icon" href="//php.net/favicon.ico">
<!--[if lt IE 9]>
  <script src="//shared.php.net/js/html5shiv.js"></script>
<![endif]-->

<style type="text/css">
table {
 margin-left: auto;
 margin-right: auto;
 text-align: left;
 border-spacing: 2px;
 font-size:14px;
}
th {
 color: white;
 background-color: #666699;
 padding: 0.2em;
 text-align: center;
 vertical-align: middle;
}
td {
 padding: 0.2em 0.3em;
}
.oc {
 white-space: nowrap;
 overflow: hidden;
 max-width: 6em;
}
.copy {
 margin:0;
 padding: 0;
 font-size:small;
 }
.copy:hover {
 text-transform: uppercase;
}
.copy:active {
 background: aqua;
 font-weight: bold;
}
.o {
 white-space: nowrap;
 overflow: hidden;
 max-width: 3em;
}
.c {
 text-align: center;
}
</style>
</head>
<body id="doc">

<div class="wrap">
<header class='clearfix'>
  <div id="mainmenu-toggle-overlay"></div>
  <input type="checkbox" id="mainmenu-toggle">
  <nav class="fullscreen">
    <div class="mainscreen">
      <a href="/" class="home"><img src="//php.net/images/logo.php?doc" width="48" height="24" alt="php"><span class="subdomain">doc</span></a>
      <ul>
        <li><a href="/revcheck.php">Documentation Tools</a></li>
        <li><a href="/tutorial/">Tutorial for Contributors</a></li>
        <li><a href="/phd.php">PhD Homepage</a></li>
      </ul>
    </div>
  </nav>
</header>
<div id="flash-message"></div>
<nav id="megadropdown"></nav>

<section class="fullscreen clearfix">
