<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <title>PHP: Documentation Tools</title>

  <link media='all' rel='stylesheet' href='//shared.php.net/styles/defaults.css?filemtime=1421836947'/>
  <link media='all' rel='stylesheet' href='//shared.php.net/styles/doc.css?filemtime=1425812404'/>

  <link href="//fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,400italic,600italic|Source+Code+Pro&amp;subset=latin,latin-ext" rel="stylesheet">
  <link rel="shortcut icon" href="//php.net/favicon.ico">
<!--[if lt IE 9]>
  <script src="//shared.php.net/js/html5shiv.js"></script>
<![endif]-->
</head>
<body id="doc">

<div class="wrap">
<header class='clearfix'>
  <div id="mainmenu-toggle-overlay"></div>
  <input type="checkbox" id="mainmenu-toggle">
  <nav class="fullscreen">
    <div class="mainscreen">
      <a href="/" class="home"><img src="//www.php.net/images/logos/php-logo.svg" width="48" height="24" alt="php"><span class="subdomain">doc</span></a>
      <ul>
        <li><a href="/guide/">How to Contribute</a></li>
        <li><a href="/revcheck.php">Translation Status</a></li>
        <li><a href="/phd.php">PhD Homepage</a></li>
      </ul>
    </div>
  </nav>
</header>
<div id="flash-message"></div>
<nav id="megadropdown"></nav>

<section class="fullscreen clearfix">
