#!/bin/sh

. `dirname $0`/../../build-ops

cd ${SCRIPTSDIR}
${PHP} checkent.php phpdoc > ${DOCWEB}/www/checkent_php.php
${PHP} checkent.php peardoc > ${DOCWEB}/www/checkent_pear.php
${PHP} checkent.php smarty > ${DOCWEB}/www/checkent_smarty.php
