#!/bin/sh

. `dirname $0`/../../build-ops

cd ${CVSDIR}/${DOCDIR}
autoconf
./configure --with-jade=/usr/local/bin/jade --with-nsgmls=/usr/local/bin/nsgmls
make howtophp
cp howto/php/* ${DOCWEB}/www/dochowto

make howtotgz
cp howto/howto.html.tar.gz ${DOCWEB}/www/dochowto
