#!/bin/sh

. `dirname $0`/../../build-ops

cd ${CVSDIR}/${DOCDIR}
php configure.php --enable-howto
php ${CVSDIR}/phd/build.php -d ${CVSDIR}/${DOCDIR}/howto/.howto.xml -t howto
mv howto/*.php ${DOCWEB}/www/dochowto/

#make howtotgz
#cp howto/howto.html.tar.gz ${DOCWEB}/www/dochowto
