#!/bin/sh
# Generate apidocs for docweb
#/home/jacques/public_html/phpdoc/phpdoc -d /home/pure-ftpd-users/php001/docs.php.mirrors.powertrip.co.za/include/ -dn 'docweb' -ti 'docweb' -pp -q -s -t /home/pure-ftpd-users/php001/docs.php.mirrors.powertrip.co.za/www/apidoc/ -o HTML:Smarty:PHP
