<!--
vim: et ts=2 sw=2 ft=html fdm=marker
-->
<?php
function bugfix($number) { echo "Fixed bug "; bugl($number); }
function bugl($number)   { echo "<a href=\"http://bugs.php.net/$number\">#$number</a>"; }
?>
<p>PhD releases:</p>

<ul id="releases">
  <li>
    <a href="/phd/PhD-0.2.2.tgz">PhD 0.2.2</a> <span class="date">30. January 2008</span><!-- {{{ -->
    <ul class="fixes">
      <li>Removed support for phnotify</li>
      <li>Added index chaching (Edward Z.)</li>
      <li>Added option (-l/--list) to list the supported formats/themes</li>
      <li>Added support for linkend in fieldsynopsis varnames</li>
      <li>Added autogenerated "Edited by" text for &lt;editor&gt;</li>
      <li>Added autogenerated "by" text for the first &lt;author&gt; element in &lt;authorgroup&gt;</li>
      <li>Added missing closing "}" for classsynopsis</li>
      <li>Fixed E_NOTICE on empty references</li>
      <li>Fixed weird error message when no arguments are given (reported by Tony)</li>
      <li>Fixed typos in the argument descriptions (--help) (reported by Tony)</li>
      <li><?php bugfix(43972); ?> (PhD doesn't warn on missing partial IDs)</li>
      <li><?php bugfix(43904); ?> (PhD doesn't detect &lt;section&gt; without xml:id)</li>
      <li><?php bugfix(43489); ?> (Class synopsis return types are not links)</li>
      <li><?php bugfix(43440); ?> (Wrong encoding on some parts of the page)</li>
      <li><?php bugfix(43428); ?> (Empty TOC)</li>
      <li><?php bugfix(43421); ?> (All intra-document hyperlinks broken in the Single HTML file form of manual)</li>
      <li><?php bugfix(43416); ?> (Function links do not render as links)</li>
    </ul><!-- }}} -->
  </li>
  <li>
  <a href="/phd/PhD-0.2.1.tgz">PhD 0.2.1</a> <span class="date">12. December 2007</span><!-- {{{ -->
    <ul class="fixes">
      <li>Multiple &lt;term&gt;s should be line seperated</li>
      <li>Fixed autogenerated links to methods (Edward Z.)</li>
      <li>Compressed methodnames in classsynopsis (Edward Z.)</li>
      <li>Added HTML headers for the bightml theme</li>
      <li>Removed warnings about missing translation files</li>
    </ul><!-- }}} -->
  </li>
  <li>
    <a href="/phd/PhD-0.2.0.tgz">PhD 0.2.0</a> <span class="date">8. November 2007</span><!-- {{{ -->
    <ul class="fixes">
      <li>Added partial rendering</li>
      <li>Added various verbosity levels</li>
      <li>Added getopt() parsing for few configuration options</li>
      <li>Added support for errorcode, symbol and superscript elements (used by few translations)</li>
      <li>Suppressed the contrib element</li>
      <li><?php bugfix(43192); ?> (Chunked HTML output difficult to use without TOC). (Edward Z. Yang)</li>
      <li><?php bugfix(43191); ?> (build.php fails to included necessary theme dependencies). (Edward Z. Yang, Richard Q)</li>
    </ul><!-- }}} -->
  </li>
  <li>
    <a href="/phd/PhD-0.1.0.tgz">PhD 0.1.0</a> <span class="date">20. October 2007</span><!-- {{{ -->
    <ul class="fixes">
      <li>Added example numbering</li>
      <li>Improved support for modifiers in fieldsynopsis</li>
      <li>Remove () from refname when looking for version info (reported by Paul Reinheimer)</li>
      <li>Print notes inline with its title (reported by Philip Olson)</li>
      <li>Check if we have an open "{" before we print "}"</li>
      <li>Escape the version info (patch by Richard Q.)</li>
      <li>Fixed variablelist titles</li>
      <li>Fixed table info titles</li>
      <li>Fixed empty table cells (reported by Mark Wiesemann)</li>
      <li>Fixed table title markup (reported by Richard Q.)</li>
      <li>Fixed non-closing b element for empty &lt;title /&gt;s (reported by Joshua Thompson and Philip Olson)</li>
      <li><?php bugfix(43013); ?> (Description rather then function name for right arrows on extension pages) (patch by Richard Q.)</li>
      <li><?php bugfix(42906); ?> (docs.php.net bold instead of links)</li>
      <li><?php bugfix(42860); ?> (cannot render &lt;orgname&gt; element)</li>
      <li><?php bugfix(42845); ?> (Copyright page has no TOC)</li>
      <li>Language support (for autogenerated texts):
        <ul>
          <li>* Bulgarian (by Kouber Saparev)</li>
          <li>* Czech (by Jakub Vrana)</li>
          <li>* German (by Oliver Albers)</li>
          <li>* Italian (by Marco Cucinato)</li>
          <li>* Japanese (by TAKAGI Masahiro)</li>
          <li>* Polish (by Jaroslaw Glowacki)</li>
          <li>* Brazilian Portuguese (by Diego Feitosa)</li>
          <li>* Romanian (by Simion Onea)</li>
        </ul>
      </li>
    </ul><!-- }}} -->
  </li>
  <li>
    <a href="/phd/PhD-0.1RC1.tgz">PhD 0.1RC1</a> <span class="date">1 October 2007</span>
    <ul class="fixes">
      <li>Initial release</li>
    </ul>
  </li>
</ul>

