<!--
vim: et ts=2 sw=2 ft=html fdm=marker
-->
<?php
function bugfix($number) { echo "Fixed bug "; bugl($number); }
function bugl($number)   { echo "<a href=\"http://bugs.php.net/$number\">#$number</a>"; }
?>
<p>PhD releases:</p>

<ul id="releases">
  <li>
    <a href="/phd/PhD-0.4.1.tgz">PhD 0.4.1</a> <span class="date">08. November 2008</span><!-- {{{ -->
    <ul class="fixes">
      <li><?php bugfix(46413);?> Weird examples in Unix manual pages (Rudy)</li>
      <li>Added varlistentries to the CHM index. (Rudy)</li>
      <li>Language support (for autogenerated texts):
        <ul>
          <li>Turkish (by Nilgün Belma Bugüner)</li>
        </ul>
      </li>
      <li>Prevent prev/next errors in combination with chunking elements without ids (Christian)</li>
      <li>Support double nested chunking elements without ids (Christian)</li>
      <li>Make table captions render properly in peardoc (Christian)</li>
      <li>add support for &lt;arg&gt; and &lt;cmdsynopsis&gt; used in peardoc (Christian)</li>
      <li><?php bugfix(46415); ?>: Don't chunk first section on parent site when it has children. (Christian)</li>
      <li>Implement request <?php bugl(46411); ?>: Allow random chunking depths (Christian)</li>
      <li>Implement request <?php bugl(46412); ?>: Allow random TOC depths (Christian)</li>
      <li>Implement request <?php bugl(46493); ?>: Implement new pear api linking tag (Christian)</li>
      <li>Make pear chm theme work (Christian)</li>
      <li>Make html generated in pear themes nearly 100% valid XHTML (Christian)</li>
      <li>Make "Prev" links work correctly on last pages (e.g. last in chapter) (Christian)</li>
      <li>Change double quotes to single ones, gives speedup for pear builds (Brett)</li>
      <li>Docblock enhancements and Coding Standards fixes (Brett)</li>
    </ul><!-- }}} -->
  </li>
  <li>
    <a href="/phd/PhD-0.4.0.tgz">PhD 0.4.0</a> <span class="date">20. October 2008</span><!-- {{{ -->
    <ul class="fixes">
      <li>Added PEAR XHTML theme. (Rudy, Christian)</li>
      <li>Added support for new elements (Christian)
        <ul>
          <li>glossentry</li>
          <li>glossdef</li>
          <li>glosslist</li>
          <li>important</li>
          <li>paramdef</li>
          <li>personblurb</li>
          <li>phrase</li>
          <li>prompt</li>
          <li>releaseinfo</li>
          <li>spanspec</li>
          <li>qandadiv</li>
        </ul>
      </li>
      <li>Improved &lt;email&gt; support (now creates mailto: links). (Christian)</li>
      <li>Chunks without xml:id are no longer chunked. (Christian)</li>
      <li><?php bugfix(46252); ?> (Class properties links to a function if theres one with the same name). (Hannes)</li>
      <li><?php bugfix(46094); ?> (and then from now on italic). (Hannes)</li>
      <li><?php bugfix(45071); ?> (Links to require/include(_once) not rendered). (Hannes)</li>
      <li>Fixed a bug where it was only possible to pass one parameter to phd.bat. (Kalle)</li>
      <li>Fixed a bug where it wasn't possible to have paths with spaces in when using phd.bat. (Kalle)</li>
      <li>Fixed xhtml validation issue for itemizedlist. (Christian)</li>
    </ul><!-- }}} -->
  </li>
  <li>
    <a href="/phd/PhD-0.3.1.tgz">PhD 0.3.1</a> <span class="date">23. August 2008</span><!-- {{{ -->
    <ul class="fixes">
      <li>Added PDF output format. (Rudy)</li>
      <li>Added support for phpdoc:classref. (Hannes)</li>
      <li>Added support for phpdoc:varentry. (Hannes)</li>
      <li>Added support for the phpdoc howto. (Hannes)</li>
      <li>Renamed phpdoc:exception to phpdoc:exceptionref. (Hannes)</li>
      <li><?php bugfix(45627); ?> (Unix manpages using non-standard folder name). (Rudy)</li>
      <li><?php bugfix(45626); ?> (Unix manpages should be gzipped). (Rudy)</li>
      <li><?php bugfix(45618); ?> (Bad filenames in man pages). (Rudy)</li>
      <li>Fixed unclosed div element on set pages. (Hannes)</li>
    </ul><!-- }}} -->
  </li>
  <li>
    <a href="/phd/PhD-0.3.0.tgz">PhD 0.3.0</a> <span class="date">24. July 2008</span><!-- {{{ -->
    <ul class="fixes">
      <li>Added CHM output format. (Rudy)</li>
      <li>Added KDevelop (Index &amp; Table of contents) output theme. (Rudy)</li>
      <li>Added Man page output format. (Rudy)</li>
      <li>Added support for phpdoc:exception. (Hannes)</li>
    </ul><!-- }}} -->
  </li>
  <li>
    <a href="/phd/PhD-0.2.4.tgz">PhD 0.2.4</a> <span class="date">24. May 2008</span><!-- {{{ -->
    <ul class="fixes">
      <li><?php bugfix(44906); ?> (Missing space after modifier in properties list). (Hannes)</li>
      <li><?php bugfix(44881); ?> (Class constants with $). (Hannes)</li>
      <li><?php bugfix(44786); ?> (Remove irrelevant version information). (Hannes)</li>
      <li><?php bugfix(44785); ?> (Separating &lt;title&gt; from &lt;note&gt;). (Hannes)</li>
      <li><?php bugfix(44776); ?> (Request for change in titles). (Hannes)</li>
      <li><?php bugfix(44750); ?> (Request for generic phd logger). (Hannes)</li>
      <li><?php bugfix(44690); ?> (Please restore manual main page). (Hannes)</li>
      <li>Added French support (for autogenerated texts). (Yannick)</li>
      <li>Added Danish support (for autogenerated texts). (Kalle Sommer)</li>
      <li>Added Swedish support (for autogenerated texts). (Kalle Sommer)</li>
      <li>Added experimental option (-c/--color) for color in verbose output. (Gwynne)</li>
    </ul><!-- }}} -->
  </li>
  <li>
    <a href="/phd/PhD-0.2.3.tgz">PhD 0.2.3</a> <span class="date">31. March 2008</span><!-- {{{ -->
    <ul class="fixes">
      <li>Added initial hCalendar support for &lt;author&gt;. (Hannes)</li>
      <li>Added initial eRDF support for &lt;refentry&gt;. (Hannes)</li>
      <li>Added support for &lt;footnote&gt; and &lt;footnoteref&gt;. (Gwynne, Hannes)</li>
      <li>Added anchor generation for various elements. (Hannes)</li>
      <li>Added option (-s/--skip) to skip rendering of chunks. (Hannes)</li>
      <li>Added option (-o/--output) to specify output directory (FR<?php bugl(43193) ?>). (Richard)</li>
      <li>Added support for &lt;sect4&gt; titles . (Gwynne)</li>
      <li>Added an 'infdec' role to &lt;literal&gt; in XHTML. (Gwynne)</li>
      <li>Fixed couple of typos in PhD info messages. (Richard Q.)</li>
      <li>Reformatted package.xml for readability and consistency. (Gwynne)</li>
      <li>Merged README.RENDERER into README and updated README with current information. (Gwynne)</li>
      <li>Gwynne is a developer of PhD, unfortunately. (Gwynne)</li>
      <li>Made 'Example #' text localizeable. (Gwynne)</li>
      <li>Added Russion support (for autogenerated texts). (Tony)</li>
      <li>Updated translations:
        <ul>
          <li>Japanese (Masahiro)</li>
          <li>Brazilian Portuguese (Felipe)</li>
          <li>German (Mark)</li>
        </ul>
      </li>
    </ul><!-- }}} -->
  </li>
  <li>
    <a href="/phd/PhD-0.2.2.tgz">PhD 0.2.2</a> <span class="date">30. January 2008</span><!-- {{{ -->
    <ul class="fixes">
      <li>Removed support for phnotify. (Hannes)</li>
      <li>Added index caching. (Edward Z.)</li>
      <li>Added option (-l/--list) to list the supported formats/themes.(Hannes)</li>
      <li>Added support for linkend in fieldsynopsis varnames. (Hannes)</li>
      <li>Added autogenerated "Edited by" text for &lt;editor&gt;. (Hannes)</li>
      <li>Added autogenerated "by" text for the first &lt;author&gt; element in &lt;authorgroup&gt;. (Hannes)</li>
      <li>Added missing closing "}" for classsynopsis. (Hannes)</li>
      <li>Fixed E_NOTICE on empty references. (Hannes)</li>
      <li>Fixed weird error message when no arguments are given, reported by Tony. (Hannes)</li>
      <li>Fixed typos in the argument descriptions (--help), reported by Tony. (Hannes)</li>
      <li><?php bugfix(43972); ?> (PhD doesn't warn on missing partial IDs). (Hannes)</li>
      <li><?php bugfix(43904); ?> (PhD doesn't detect &lt;section&gt; without xml:id). (Hannes)</li>
      <li><?php bugfix(43489); ?> (Class synopsis return types are not links). (Hannes)</li>
      <li><?php bugfix(43440); ?> (Wrong encoding on some parts of the page). (Hannes)</li>
      <li><?php bugfix(43428); ?> (Empty TOC). (Hannes)</li>
      <li><?php bugfix(43421); ?> (All intra-document hyperlinks broken in the Single HTML file form of manual). (Hannes)</li>
      <li><?php bugfix(43416); ?> (Function links do not render as links). (Hannes)</li>
    </ul><!-- }}} -->
  </li>
  <li>
  <a href="/phd/PhD-0.2.1.tgz">PhD 0.2.1</a> <span class="date">12. December 2007</span><!-- {{{ -->
    <ul class="fixes">
      <li>Multiple &lt;term&gt;s should be line seperated. (Hannes)</li>
      <li>Fixed autogenerated links to methods. (Edward Z.)</li>
      <li>Compressed methodnames in classsynopsis. (Edward Z.)</li>
      <li>Added HTML headers for the bightml theme. (Hannes)</li>
      <li>Removed warnings about missing translation files. (Hannes)</li>
    </ul><!-- }}} -->
  </li>
  <li>
    <a href="/phd/PhD-0.2.0.tgz">PhD 0.2.0</a> <span class="date">8. November 2007</span><!-- {{{ -->
    <ul class="fixes">
      <li>Added partial rendering. (Hannes)</li>
      <li>Added various verbosity levels. (Hannes)</li>
      <li>Added getopt() parsing for few configuration options. (Hannes)</li>
      <li>Added support for errorcode, symbol and superscript elements (used by few translations). (Hannes)</li>
      <li>Suppressed the contrib element. (Hannes)</li>
      <li><?php bugfix(43192); ?> (Chunked HTML output difficult to use without TOC). (Edward Z. Yang)</li>
      <li><?php bugfix(43191); ?> (build.php fails to included necessary theme dependencies). (Edward Z. Yang, Richard Q)</li>
    </ul><!-- }}} -->
  </li>
  <li>
    <a href="/phd/PhD-0.1.0.tgz">PhD 0.1.0</a> <span class="date">20. October 2007</span><!-- {{{ -->
    <ul class="fixes">
      <li>Added example numbering. (Hannes)</li>
      <li>Improved support for modifiers in fieldsynopsis. (Hannes)</li>
      <li>Remove () from refname when looking for version info, reported by Paul Reinheimer. (Hannes)</li>
      <li>Print notes inline with its title, reported by Philip Olson. (Hannes)</li>
      <li>Check if we have an open "{" before we print "}". (Hannes)</li>
      <li>Escape the version info. (Richard Q.)</li>
      <li>Fixed variablelist titles. (Hannes)</li>
      <li>Fixed table info titles. (Hannes)</li>
      <li>Fixed empty table cells, reported by Mark Wiesemann. (Hannes)</li>
      <li>Fixed table title markup, reported by Richard Q. (Hannes)</li>
      <li>Fixed non-closing b element for empty &lt;title /&gt;s, reported by Joshua Thompson and Philip Olson. (Hannes)</li>
      <li><?php bugfix(43013); ?> (Description rather then function name for right arrows on extension pages). (Richard Q.)</li>
      <li><?php bugfix(42906); ?> (docs.php.net bold instead of links). (Hannes)</li>
      <li><?php bugfix(42860); ?> (cannot render &lt;orgname&gt; element). (Hannes)</li>
      <li><?php bugfix(42845); ?> (Copyright page has no TOC). (Hannes)</li>
      <li>Language support (for autogenerated texts):
        <ul>
          <li>Bulgarian (by Kouber Saparev)</li>
          <li>Czech (by Jakub Vrana)</li>
          <li>German (by Oliver Albers)</li>
          <li>Italian (by Marco Cucinato)</li>
          <li>Japanese (by TAKAGI Masahiro)</li>
          <li>Polish (by Jaroslaw Glowacki)</li>
          <li>Brazilian Portuguese (by Diego Feitosa)</li>
          <li>Romanian (by Simion Onea)</li>
        </ul>
      </li>
    </ul><!-- }}} -->
  </li>
  <li>
    <a href="/phd/PhD-0.1RC1.tgz">PhD 0.1RC1</a> <span class="date">1 October 2007</span>
    <ul class="fixes">
      <li>Initial release</li>
    </ul>
  </li>
</ul>

