#!/bin/sh

# This task run two shell scripts responsible for revision check
# - populatedocs.sh - checking out SVN docs repository into local filesystem
# - generation.sh - generating revision check database and charts

. `dirname $0`/../../build-ops

cd ${SCRIPTSDIR}

./populatedocs.sh
./generation.sh
